name       : libzen
version    : 0.4.38
release    : 5
source     :
    - https://old.mediaarea.net/download/source/libzen/0.4.38/libzen_0.4.38.tar.xz : b8825b3190b3a31d8d362547cfa26a3c10e8c063df2d87e4a05758d6b756c8ab
license    : Zlib
component  : programming
summary    : Small C++ derivate classes to have an easier life
description: |
    ZenLib is a C++ utility library. It includes classes for handling strings, configuration, bit streams, threading, translation, and cross-platform operating system functions.
setup      : |
    pushd Project/GNU/Library
    %autogen --enable-shared --disable-static
build      : |
    pushd Project/GNU/Library
    %make
install    : |
    pushd Project/GNU/Library
    %make_install
