name       : libzen
version    : 0.4.33
release    : 1
source     :
    - https://mediaarea.net/download/source/libzen/0.4.33/libzen_0.4.33.tar.bz2 : a289197a24ca94c506abab3113a1af2dcc82bc97736b23e02fd57ca99e8ac55f
license    : zlib
component  : programming
summary    : Small C++ derivate classes to have an easier life
description: |
    Small C++ derivate classes to have an easier life
setup      : |
    cd Project/GNU/Library
    %autogen --enable-shared --disable-static
build      : |
    cd Project/GNU/Library
    %make
install    : |
    cd Project/GNU/Library
    %make_install
