name       : libzen
version    : 0.4.37
release    : 4
source     :
    - https://mediaarea.net/download/source/libzen/0.4.37/libzen_0.4.37.tar.xz : 401c34d93056a95f8392982f856d1371c5de6aec373d84dcbb356e1f473d0452
license    : zlib
component  : programming
summary    : Small C++ derivate classes to have an easier life
description: |
    ZenLib is a C++ utility library. It includes classes for handling strings,
    configuration, bit streams, threading, translation, and cross-platform
    operating system functions.
setup      : |
    pushd Project/GNU/Library
    %autogen --enable-shared --disable-static
build      : |
    pushd Project/GNU/Library
    %make
install    : |
    pushd Project/GNU/Library
    %make_install
