name       : libzen
version    : 0.4.36
release    : 3
source     :
    - https://mediaarea.net/download/source/libzen/0.4.36/libzen_0.4.36.tar.bz2 : 69ba2c1278b226dc83b141de63e804b417f527dfff8a816e5ffad87700f3ed5c
license    : zlib
component  : programming
summary    : Small C++ derivate classes to have an easier life
description: |
    ZenLib is a C++ utility library. It includes classes for handling strings,
    configuration, bit streams, threading, translation, and cross-platform
    operating system functions.
setup      : |
    pushd Project/GNU/Library
    %autogen --enable-shared --disable-static
build      : |
    pushd Project/GNU/Library
    %make
install    : |
    pushd Project/GNU/Library
    %make_install
