name       : libzen
version    : 0.4.41
release    : 9
source     :
    - https://mediaarea.net/download/source/libzen/0.4.41/libzen_0.4.41.tar.bz2 : eb237d7d3dca6dc6ba068719420a27de0934a783ccaeb2867562b35af3901e2d
license    : Zlib
component  : programming
summary    : Small C++ derivate classes to have an easier life
description: |
    ZenLib is a C++ utility library. It includes classes for handling strings, configuration, bit streams, threading, translation, and cross-platform operating system functions.
setup      : |
    pushd Project/GNU/Library
    %autogen --enable-shared --disable-static
build      : |
    pushd Project/GNU/Library
    %make
install    : |
    pushd Project/GNU/Library
    %make_install
